# Generated by Django 4.2.6 on 2024-07-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=50)),
                ('cinemaTheatre', models.CharField(max_length=100)),
                ('showTime', models.CharField(max_length=50)),
                ('patronName', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=50)),
                ('seatNo', models.CharField(max_length=50)),
                ('seatSeries', models.CharField(max_length=10)),
                ('movieDate', models.CharField(max_length=30)),
            ],
        ),
    ]
